### ISSUE TITLE
Lack of guidelines for development

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hoprnet-org#100]
# Introduction

There are currently a few individuals working on our project, yet, there are very little guidelines on how to interact with the project.

# Task description

- [ ] Update the README.md to include some Contribution Guidelines on the repository.

# Definition of complete

The task is completed when people understand the following:
- How to create an issue?
- How to solve an issue?
- Which branch convention name is to be used?
- Which commit convention is to be used?

# Testing criteria

- [ ] The README.md explains how to open an issue found in the website.
- [ ] The README.md explains how to run the project and submit a pull-request.
- [ ] The README.md explains how to name our branches before sending a pull-request.
- [ ] The README.md explains which conventions to be used for our website.
