### ISSUE TITLE
Add new partner: Blockark.io

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hoprnet-org#117]
# Introduction

We got new partners!

# Task description

- [ ] Add blockark.io logo and link to the website

# Definition of complete

Blockark is included as a partner in all pages in our site that has a "partners" section.

# Testing criteria

- [ ] Blockark added in /token
- [ ] Blockark added in /win
- [ ] Blockark added in /about-us

# Additional notes

Find the logos attached.
[BLOCKARK-LOGO（透明）.zip](https://github.com/hoprnet/hoprnet-org/files/6007751/BLOCKARK-LOGO.zip)
