### ISSUE TITLE
/win - Quiz-section: Add Vimeo-sample destination

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#130]
# Introduction
When people visit `/win` at 7 am CET, the "quiz" mode of the website will start. The quiz mode shows a video with questions asked by one of the three founders of HOPR, and can only be solved by watching the video and knowing about HOPR. The idea is that only during the destination hour (each destination is meant to be "available" only for one hour only), the website shows the specific question for that specific destination. Thus, we update the video to show per question, showing each video at a given time.

# Task Description
![image](https://user-images.githubusercontent.com/1128312/108762836-df5a4280-7550-11eb-9f40-07e0864a8fce.png)

The task is simple: add a video that gets updated every time that the time changes. We are making the assumption people will keep the page open all the time (the prize is worth it!), so the video needs to change every time the video changes. For testing, we recommend using a different timezone than the ones needed (e.g. changes every 1 minute).

- [ ] Add a Video component showing the "current video" to be shown at the current destination.
  - [ ] Using `fetch`, call `api.hoprnet.org/fetchVideo`, which will return a JSON like this: `{ video: "https://vimeo.com/512589722" }`
  - [ ] Whenever the endpoint fails or returns empty, use the default sample video URL.
- [ ] Provide a Tweet button with a template for people to submit the answer:
  - [ ] Add an input field where people can type the answer for the quiz
  - [ ] Ensure the template given to the tweet updates every destination change
- [ ] Provide a slider animation to smoothly open/close the existing destination, showing the current one only (past versions should be shown as disabled and can't be seen anymore). See the Figma link, under "Prototype", to get an idea.

# Additional Notes
The quiz should function as a stateless app that can be easily tested by only updating the hours of the destinations so one can simply see the application open/close every time a new destination is achieved. For now, the only video that needs to be shown is the sample one, and the endpoint will be responsible for fetching the correct video URL. The page just needs to make sure it calls the endpoint at the correct time, so it gets updated.

# Important Links
- Figma [Link](https://www.figma.com/file/upymHt7FzMhCraUi6ziSRK/hopr_Token_Website_15_ALL_DEVICES?node-id=424%3A0). Check the prototype mode to have an idea of how it looks.
- Sample video - https://vimeo.com/512589722
- Destinations and Tags:

Destination | Tags
-- | --
Tokyo | #Tokyo #HOPRlaunch
Seoul | #Seoul #HOPRlaunch
Shanghai | #Shanghai #HOPRlaunch
Hanoi | #Hanoi #HOPRlaunch
Moscow | #Moscow #HOPRlaunch
Istanbul | #Istanbul #HOPRlaunch
Zurich | #Zurich #HOPRlaunch
Madrid | #Madrid #HOPRlaunch
Sao Paolo | #SaoPaolo #HOPRlaunch
San Francisco | #SanFrancisco #HOPRlaunch

**Comment by ReinhardSchmidt** [comment]
FYI: Exporting the final footage currently and will discuss it with Rik tomorrow morning CET. Afterwards I will and have to be able to provide you the final vimeo-links – it's time ofc.
