### ISSUE TITLE
Organize all content into locales

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hoprnet-org#250]
# Introduction

Currently, some of the content of the website is being pulled from our JavaScript files as HTML (e.g. [use cases](https://github.com/hoprnet/hoprnet-org/blob/development/service/components/home-sections/UseCases.js#L6-L14)), some is actually being embedded as text (e.g. [use cases again](https://github.com/hoprnet/hoprnet-org/blob/development/service/components/home-sections/UseCases.js#L67-L69)) and some are dynamically generated (e.g. [win contest](https://github.com/hoprnet/hoprnet-org/blob/development/service/components/molecules/win-schedule.js#L125)). As a result, modifying the content in the website is often challenging and not easy to do. Ideally, **all content** comes from the [locales](https://github.com/hoprnet/hoprnet-org/tree/development/service/locales) directory. As of the time of writing, the content from the locales is only used in the `/token` page.

# Task Description
The following epic's goal is to simplify the existing structure of the website by listing all the places where the content does not exist in `locales` and creating the tasks to ensure this is the case. After this is completed, all the content for the entire website should be in a single folder, and modifying a particular part of the site should be something easy to do.

# Tasks

1. [ ] #245 - [Move content from components to locales](https://github.com/hoprnet/hoprnet-org/issues/245)
2. [ ] #246 - [Clean up locales to not only be used for /token](https://github.com/hoprnet/hoprnet-org/issues/245)
3. [ ] #247 - [Update documentation to reflect the location of all content pages](https://github.com/hoprnet/hoprnet-org/issues/247)
4. [ ] #248 - [Ensure the dev mode is actually useful for the entire site and not only token](https://github.com/hoprnet/hoprnet-org/issues/248)
5. [ ] #249 - [Clean up locales to avoid copy and pasted content from English and import it instead](https://github.com/hoprnet/hoprnet-org/issues/249)

**Comment by ReinhardSchmidt** [comment]
@jjperezaguinaga when can we close this?
